import Home from "./Home";
import Stacks from "./Stacks";
import StacksMore from "./Stacks/StacksMore";
import StacksCrud from "./Stacks/StacksCrud";
import Teachers from "./Teachers";
import Students from "./Students";
import Admins from "./Admins";
import Rooms from "./Rooms";
import Groups from "./Groups";
export { Home, Stacks, Teachers, Students, Admins, Rooms, Groups, StacksCrud, StacksMore };
